name: Deploy to Production

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install and build frontend
      working-directory: ./frontend
      run: |
        npm ci
        npm run build
        
    - name: Install and build backend
      working-directory: ./backend
      run: |
        npm ci
        npm run build

    - name: Deploy to server via SSH
      uses: easingthemes/ssh-deploy@v4.1.10
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        SOURCE: "./"
        TARGET: "/home/${{ secrets.REMOTE_USER }}/discovery_platform_temp/"
        EXCLUDE: |
          .git/
          .github/
          node_modules/
          backend/uploads/
          backend/.env
          frontend/.env
          *.log
          .DS_Store
          
    - name: Execute deployment script on server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/discovery_platform_temp
          bash deploy-on-server.sh