name: Deploy to Production

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Cache dependencies and builds
      uses: actions/cache@v4
      id: cache
      with:
        path: |
          ~/.npm
          frontend/node_modules
          backend/node_modules
          frontend/node_modules/.cache
        key: ${{ runner.os }}-deps-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-deps-

    - name: Install and build frontend
      working-directory: ./frontend
      env:
        # Optimization flags for faster builds
        CI: false
        GENERATE_SOURCEMAP: false
        INLINE_RUNTIME_CHUNK: false
        IMAGE_INLINE_SIZE_LIMIT: 0
        NODE_OPTIONS: --max-old-space-size=4096
        # Disable eslint during build for speed
        DISABLE_ESLINT_PLUGIN: true
        # Use faster JavaScript transformer
        FAST_REFRESH: false
        # Disable unnecessary features
        TSC_COMPILE_ON_ERROR: true
        ESLINT_NO_DEV_ERRORS: true
      run: |
        # Use cached node_modules if available, otherwise install
        if [ ! -d "node_modules" ]; then
          echo "Installing frontend dependencies..."
          npm ci --legacy-peer-deps --prefer-offline --no-audit --no-fund
        else
          echo "✓ Using cached node_modules"
        fi
        # Build with optimizations
        npm run build
        

    - name: Install and build backend
      working-directory: ./backend
      env:
        NODE_OPTIONS: --max-old-space-size=2048
      run: |
        # Use cached node_modules if available, otherwise install
        if [ ! -d "node_modules" ]; then
          echo "Installing backend dependencies..."
          npm ci --prefer-offline --no-audit --no-fund
        else
          echo "✓ Using cached node_modules"
          # Prisma might need regeneration even with cache
          npx prisma generate
        fi
        npm run build

    - name: Create deployment archive
      run: |
        tar czf deploy.tar.gz \
          --exclude='deploy.tar.gz' \
          --exclude='.git' \
          --exclude='.github' \
          --exclude='frontend/node_modules' \
          --exclude='backend/.env*' \
          --exclude='*.log' \
          --exclude='.DS_Store' \
          --warning=no-file-changed \
          .
        ls -lh deploy.tar.gz

    - name: Deploy via SCP and execute
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "deploy.tar.gz"
        target: "/tmp/"
        timeout: 10m
        command_timeout: 10m

    - name: Extract and deploy on server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        command_timeout: 30m
        script: |
          # Extract archive
          mkdir -p /var/www/vhosts/cfoeducation.it/discovery_platform_temp
          cd /var/www/vhosts/cfoeducation.it/discovery_platform_temp
          tar xzf /tmp/deploy.tar.gz
          rm /tmp/deploy.tar.gz

          # Run deployment
          bash deploy-on-server.sh